import jpg from "../daim.jpeg";
import _ from "lodash";
import "./index.scss";
import Name from "./script";
const img = document.getElementById("img");
img.src = jpg;
img.classList.add("img");
// document.body.appendChild(img);
const name = new Name("HEllo");
console.log(name);
console.log(_.random());
console.log(_.random());
